### ISSUE TITLE
使用vs2017 打开后，还需要重新配置吗？

### ISSUE THREAD

**Issue by Misng** [xfirefly/live555_vs2017#1]
![图片](https://user-images.githubusercontent.com/16435001/102770371-fea4ea00-43be-11eb-99da-18494c4fb108.png)

**Comment by Misng** [comment]
`3>c:\users\admin\downloads\compressed\live555_vs2017-master\livemedia\inputfile.cpp(21): fatal error C1083: 无法打开包括文件: “InputFile.hh”: No such file or directory
3>JPEGVideoRTPSink.cpp
3>c:\users\admin\downloads\compressed\live555_vs2017-master\livemedia\jpegvideortpsink.cpp(21): fatal error C1083: 无法打开包括文件: “JPEGVideoRTPSink.hh”: No such file or directory
3>JPEGVideoRTPSource.cpp
3>c:\users\admin\downloads\compressed\live555_vs2017-master\livemedia\jpegvideortpsource.cpp(21): fatal error C1083: 无法打开包括文件: “JPEGVideoRTPSource.hh”: No such file or directory
3>JPEGVideoSource.cpp
3>c:\users\admin\downloads\compressed\live555_vs2017-master\livemedia\jpegvideosource.cpp(21): fatal error C1083: 无法打开包括文件: “JPEGVideoSource.hh”: No such file or directory
3>live555MediaServer.cpp
3>c:\users\admin\downloads\compressed\live555_vs2017-master\livemedia\live555mediaserver.cpp(20): fatal error C1083: 无法打开包括文件: “BasicUsageEnvironment.hh”: No such file or directory
3>Locale.cpp
3>c:\users\admin\downloads\compressed\live555_vs2017-master\livemedia\locale.cpp(22): fatal error C1083: 无法打开包括文件: “Locale.hh”: No such file or directory
3>MatroskaDemuxedTrack.cpp
3>c:\users\admin\downloads\compressed\live555_vs2017-master\livemedia\matroskademuxedtrack.hh(25): fatal error C1083: 无法打开包括文件: “FramedSource.hh”: No such file or directory
3>MatroskaFile.cpp
3>c:\users\admin\downloads\compressed\live555_vs2017-master\livemedia\streamparser.hh(25): fatal error C1083: 无法打开包括文件: “FramedSource.hh”: No such file or directory
3>MatroskaFileParser.cpp
3>c:\users\admin\downloads\compressed\live555_vs2017-master\livemedia\streamparser.hh(25): fatal error C1083: 无法打开包括文件: “FramedSource.hh”: No such file or directory
3>MatroskaFileServerDemux.cpp
3>c:\users\admin\downloads\compressed\live555_vs2017-master\livemedia\matroskafileserverdemux.cpp(21): fatal error C1083: 无法打开包括文件: “MatroskaFileServerDemux.hh”: No such file or directory
3>MatroskaFileServerMediaSubsession.cpp
3>c:\users\admin\downloads\compressed\live555_vs2017-master\livemedia\matroskafileservermediasubsession.hh(26): fatal error C1083: 无法打开包括文件: “FileServerMediaSubsession.hh”: No such file or directory`

**Comment by xfirefly** [comment]
我也忘记了, 应该是不需要, 我当时编译过
